buildscript {
    repositories {
        google() // Google 仓库（Gradle 插件在这里）
        mavenCentral() // 中央仓库
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:9.1.0'
        classpath 'org.jetbrains.kotlin:kotlin-gradle-plugin:2.3.20'
    }
}
// 项目仓库配置（给 App 依赖用）
allprojects {
    repositories {
        google()
        mavenCentral()
    }
}
// 1. 仓库配置（必须放在 buildscript 外部）
allprojects {
    repositories {
        google() // Google Maven 仓库
        mavenCentral() // Maven 中央仓库
    }
}
android {
    compileSdkVersion 36
    defaultConfig {
        applicationId "org.somebody.hcode"
        minSdkVersion 23
        targetSdkVersion 36
        versionCode 1
        versionName "1.0"
        namespace "org.somebody.hcode" // 替换为你的包名
        }
    lintOptions {
        checkReleaseBuilds false
        abortOnError false
        }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    buildFeatures {
        compose true
    }
    composeOptions {
        kotlinCompilerExtensionVersion "2.3.20" // 需与Kotlin版本匹配
    }
    sourceSets {
        main {
            // 2. 指定JNI库的存放路径（默认是src/main/jniLibs）
            jniLibs.srcDirs = ['libs']  // 若库在libs目录下
        }
    }
}
dependencies {
    // 基础依赖
    implementation 'androidx.core:core-ktx:1.18.0'
    implementation 'androidx.compose.ui:ui:1.10.5'
    implementation 'androidx.compose.material:material:1.10.5'
    implementation 'androidx.activity:activity-compose:1.13.0'
    implementation 'org.jetbrains.kotlin:kotlin-stdlib:2.3.20'
}
