buildscript {
    repositories {
        google()
        mavenCentral()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle' // 插件依赖写在这里
    }
}
dependencies {
    implementation 'androidx.appcompat:appcompat'
    implementation 'com.google.android.material:material'
    implementation 'androidx.constraintlayout:constraintlayout'
    implementation 'androidx.wear:wear'
}
