// 1. 声明项目包含的模块
include ':lib'  // 包含library模块

// 2. 配置仓库（Android项目常用）
dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        google()  // Google Maven仓库
        mavenCentral()  // Maven中央仓库
    
    }
}

 
rootProject.name = "org.somebody.hcode"
include ':'
