
buildscript {
    repositories {
        // 添加Google Maven仓库
        google()
        mavenCentral()
    }
    dependencies {
        // 添加Android Gradle插件依赖（替换为你需要的版本）
        classpath 'com.android.tools.build:gradle:7.0.2'
    }
}

allprojects {
    repositories {
        google()
        mavenCentral()
    }
}
 
rootProject.name = "org.somebody.hcode"
include ':'
