// 1. 声明项目包含的模块
include ':libs'  // 包含library模块
include ':'
rootProject.name = "org.somebody.hcode"
// 2. 配置仓库（Android项目常用）
dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        // 添加Google Maven仓库
        google()
        mavenCentral()
    }
}
