name: MD5 Crack (Manual Trigger)

on:
  workflow_dispatch:  # 仅保留手动触发

jobs:
  build-and-run:
    runs-on: ubuntu-slim
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Zig
  # You may pin to the exact commit or the version.
  # uses: jetsung/setup-zig@ece60a5f01428e90311476245667dc49e3f84513
        uses: jetsung/setup-zig@v0.0.4
        with:
    # Zig version (e.g. 0.15.2, dev, master). Leave empty for latest stable.
          version: 0.15.0 # optional, default is 
          

      

      - name: Install Zig crypto package
        run: zig init 
      - name: Build program
        run: zig build-exe main.zig -O ReleaseFast
      - name: Run program
        run: ./main
